<?php
/**
* @var SmartOSC\Article\Block\Display $block
*/
?>
<style>

.card {
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    margin:10px;
    padding: 5px;
}

.card:hover {
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}

.container {
    padding: 2px 16px;
}
.detail_button{
    text-align: right;
}

.block-title{
    text-align: center;
}

#block-title{
    font-weight: bold;
}

</style>
<div class="block-title">
    <h2 id="block-title"> Article List </h2>
</div>
<div class="list_article">
    <?php foreach ($block->getArticleCollection() as $key=>$article){ ?>
        <div class="card">
            <div class="container">
                <div class="article_title">
                    <a href="/magento/article/detail/detail/?id=<?= $article->getId() ?>">
                        <h3><?= __($article->getTitle()) ?></h3>
                    </a>
                </div>
                <div class="detail_button">
                    <button onclick="window.location.href='http://localhost/magento/article/detail/detail/?id=<?= $article->getId() ?>'" >Chi tiết</button>
                </div>
            </div>
        </div>
    <?php } ?>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml(); ?></div>
    <?php endif ?>

</div>
