<?php
/**
 * @var SmartOSC\Article\Block\Display $block
 */
echo $block->displayArticle();
?>

<style>
.post-id{
    width:2%
}
.post-name{
    width:30%
}
.card {
    /* Add shadows to create the "card" effect */
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    margin:10px;
    padding: 5px;
}

/* On mouse-over, add a deeper shadow */
.card:hover {
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}

/* Add some padding inside the card container */
.container {
    padding: 2px 16px;
}
.detail_button{
    text-align: right;
}

</style>

<div>
    <?php
        foreach ($block->getArticleCollection() as $key=>$article){
            echo '<div class="card">
                    <div class="container">    
                        <div class="article_title">
                            <a href="/">
                                <h3>'.$article->getTitle().'</h3>                        
                            </a>
                        </div>
                        <div class="detail_button">
                            <button>Detail</button>
                        </div>
                    </div>
                  </div>';
        }
    ?>
</div>

</body>
</html>